export const DESKTOP_BRIDGE_CAPABILITIES = [
  "openFile",
  "openSubtitleFile",
  "readFile",
  "showSaveDialog",
  "selectDirectory",
  "showInExplorer",
  "fetchCookies",
  "getPathForFile",
  "writeFile",
  "getFileSize",
  "getDesktopRuntimeInfo",
  "minimize",
  "maximize",
  "close",
  "notifyRendererReady",
] as const;
