// Generated by scripts/generate_frontend_api_types.py from backend.models.schemas.
// Do not edit by hand.

import type { SubtitleSegment } from "./task";

export interface TaskResponse {
  task_id: string;
  status: string;
  message?: string;
}

export interface TranslateResponse {
  task_id: string;
  status: string;
  segments?: SubtitleSegment[] | null;
}
