// Generated by scripts/generate_frontend_api_types.py from backend wire models.
// Do not edit by hand.

export type TranslationTargetLanguage = "SimplifiedChinese" | "TraditionalChinese" | "English" | "Japanese" | "Spanish" | "French" | "German" | "Russian";
export interface MediaReference {
  path: string;
  name: string;
  size?: number | null;
  type?: string | null;
  media_id?: string | null;
  media_kind?: string | null;
  role?: string | null;
  origin?: string | null;
}
export interface TaskArtifact {
  kind: "video" | "audio" | "subtitle" | "image" | "file";
  role: "input" | "output" | "context";
  ref: MediaReference;
}
export interface TaskResult {
  success: boolean;
  artifacts?: TaskArtifact[];
  meta?: Record<string, unknown>;
  error?: string | null;
}
export interface TranscribeRequest {
  audio_ref: MediaReference;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
}
export interface TranscribeSegmentRequest {
  audio_ref: MediaReference;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
  start: number;
  end: number;
}
export interface SubtitleSegment {
  id: string | number;
  start: number;
  end: number;
  text: string;
}
export interface TranscribeSegmentData {
  text: string;
  segments: SubtitleSegment[];
}
export interface TranscribeSegmentResponse {
  status: "completed";
  data: TranscribeSegmentData;
}
export interface TaskSubmissionMetadata {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  revision: number;
}
export interface TaskResponse {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  revision: number;
  task_id: string;
  status: string;
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
}
export interface TaskActionResponse {
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
}
export interface TaskStatusActionResponse {
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
  status: string;
}
export interface TaskCountActionResponse {
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
  count: number;
}
export interface TaskDeleteActionResponse {
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
  task_id: string;
}
export interface TaskQueueSummary {
  max_concurrent: number;
  running: number;
  queued: number;
}
export interface HealthResponse {
  status: string;
  service: string;
  version: string;
}
export interface TaskView {
  id: string;
  type: string;
  status: string;
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  progress: number;
  revision: number;
  name?: string | null;
  message_code: string;
  message_params: Record<string, string | number | boolean | null>;
  error?: string | null;
  result?: TaskResult | null;
  request_params?: Record<string, unknown> | null;
  primary_operation: string;
  artifacts?: TaskArtifact[];
  created_at: number;
  queue_state: string;
  queue_position?: number | null;
}
export interface ImmediateTranslationResponse {
  status: "completed";
  segments: SubtitleSegment[];
  language: string;
  context_ref?: MediaReference | null;
  subtitle_ref?: MediaReference | null;
  mode: string;
}
export interface DownloadParams {
  url: string;
  format?: string;
  proxy?: string | null;
  output_dir?: string | null;
  playlist_title?: string | null;
  playlist_items?: string | null;
  download_subs?: boolean;
  resolution?: string;
  cookie_file?: string | null;
  output_filename?: string | null;
  filename?: string | null;
  codec?: string;
}
export interface TranscribeParams {
  audio_ref?: MediaReference | null;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
}
export interface TranslateParams {
  context_ref?: MediaReference | null;
  target_language?: TranslationTargetLanguage;
  mode?: string;
  batch_size?: number;
}
export interface TranslationRequest {
  segments: SubtitleSegment[];
  target_language?: TranslationTargetLanguage;
  mode?: string;
  context_ref?: MediaReference | null;
  batch_size?: number;
}
export interface SynthesizeParams {
  video_ref?: MediaReference | null;
  srt_ref?: MediaReference | null;
  output_ref?: MediaReference | null;
  watermark_ref?: MediaReference | null;
  options?: Record<string, unknown> | null;
}
export interface SynthesisRequest {
  video_ref: MediaReference;
  srt_ref?: MediaReference | null;
  watermark_ref?: MediaReference | null;
  output_ref?: MediaReference | null;
  options?: Record<string, unknown> | null;
}
export interface MediaVisibleStartRequest {
  video_ref: MediaReference;
}
export interface MediaVisibleStartResponse {
  visible_start: number;
  has_leading_black: boolean;
}
export interface EditorPreviewMediaRequest {
  video_ref: MediaReference;
}
export interface EditorPreviewMediaResponse {
  source_ref: MediaReference;
  media_ref: MediaReference;
  remuxed: boolean;
}
export interface ImagePreviewResponse {
  png_path: string;
  data_url: string;
  width: number;
  height: number;
}
export interface ClipCandidate {
  id: string;
  start: number;
  end: number;
  title?: string | null;
  reason?: string | null;
  score: number;
  transcript?: string | null;
  selected: boolean;
}
export interface HighlightDetectionRequest {
  video_ref: MediaReference;
  subtitle_segments?: SubtitleSegment[];
  max_candidates?: number;
  min_duration?: number;
  max_duration?: number;
}
export interface HighlightDetectionResponse {
  candidates: ClipCandidate[];
  source: "llm";
  duration: number;
}
export interface ClipExportSegment {
  id: string;
  start: number;
  end: number;
  title?: string | null;
}
export interface ClipExportRequest {
  video_ref: MediaReference;
  segments: ClipExportSegment[];
  render_mode?: "burned" | "source";
  srt_ref?: MediaReference | null;
  watermark_ref?: MediaReference | null;
  options?: Record<string, unknown> | null;
  output_dir?: string | null;
}
export interface PipelineStepRequest {
  step_name: string;
  params: DownloadParams | TranscribeParams | TranslateParams | SynthesizeParams;
}
export interface PipelineRequest {
  pipeline_id?: string;
  task_name?: string | null;
  steps: PipelineStepRequest[];
}
export interface PlaylistItem {
  index: number;
  title: string;
  url: string;
  duration?: number | null;
  uploader?: string | null;
}
export interface AnalyzeResult {
  type: string;
  platform?: string | null;
  id?: string | null;
  title: string;
  url: string;
  direct_src?: string | null;
  thumbnail?: string | null;
  duration?: number | null;
  count?: number | null;
  items?: PlaylistItem[] | null;
  uploader?: string | null;
  webpage_url?: string | null;
  extra_info?: Record<string, unknown> | null;
}
export interface GlossaryTerm {
  id: string;
  source: string;
  target: string;
  note?: string | null;
  category?: string | null;
}
export interface CreateGlossaryTermRequest {
  source: string;
  target: string;
  note?: string | null;
  category?: string;
}
export interface UpdateGlossaryTermRequest {
  source?: string | null;
  target?: string | null;
  note?: string | null;
  category?: string | null;
}
export interface GlossaryDeleteResponse {
  status: "ok";
}
export interface AnalyzeRequest {
  url: string;
}
export interface DetectSilenceRequest {
  audio_ref: MediaReference;
  threshold?: string;
  min_duration?: number;
}
export interface DetectSilenceResponse {
  silence_intervals: unknown[][];
}
export interface CookieSaveRequest {
  domain: string;
  cookies: Record<string, unknown>[];
}
export interface CookieStatusResponse {
  domain: string;
  has_valid_cookies: boolean;
  cookie_path?: string | null;
}
export interface CookieClearResponse {
  success: boolean;
  domain: string;
}
export interface ActiveProviderRequest {
  provider_id: string;
}
export interface ProviderConnectionRequest {
  name?: string | null;
  base_url: string;
  api_key: string;
  model: string;
}
export interface ActiveProviderResponse {
  status: string;
  active_provider_id: string;
}
export interface ProviderConnectionResponse {
  status: string;
  message: string;
}
export interface ToolUpdateResponse {
  status: string;
  message: string;
  previous_version?: string | null;
  current_version?: string | null;
}
export interface FasterWhisperCliInstallResponse {
  status: string;
  message: string;
  cli_path: string;
  version?: string | null;
}
export interface FasterWhisperCliPrewarmRequest {
  model?: string;
  device?: string;
}
export interface FasterWhisperCliPrewarmResponse {
  status: string;
  message: string;
}
export interface RuntimeDependencyCheck {
  key: string;
  label: string;
  status: string;
  detail: string;
  path?: string | null;
  version?: string | null;
}
export interface CudaReadinessResponse {
  status: string;
  summary: string;
  gpu_name?: string | null;
  driver_version?: string | null;
  driver_cuda_capability?: string | null;
  dependencies: RuntimeDependencyCheck[];
  install_guidance: string[];
}
export interface LLMProvider {
  id: string;
  name: string;
  base_url: string;
  api_key: string;
  model: string;
  is_active?: boolean;
}
export interface UserSettings {
  llm_providers?: LLMProvider[];
  default_download_path?: string | null;
  faster_whisper_cli_path?: string | null;
  language?: string;
  auto_execute_flow?: boolean;
  smart_split_text_limit?: number;
  ui_state?: Record<string, unknown>;
}
export interface UserPreferencesPatch {
  llm_providers?: LLMProvider[] | null;
  default_download_path?: string | null;
  faster_whisper_cli_path?: string | null;
  language?: string | null;
  auto_execute_flow?: boolean | null;
  smart_split_text_limit?: number | null;
}
export interface UiStatePatch {
  updates?: Record<string, unknown>;
  remove?: string[];
}
export interface AsrExecutionPreferences {
  engine?: string;
  model?: string;
  device?: string;
}
