// Generated by scripts/generate_frontend_api_types.py from backend.models.schemas.
// Do not edit by hand.

export interface PipelineStepRequest {
  step_name: string;
  params: unknown;
}
export interface MediaReference {
  path: string;
  name: string;
  size?: number | null;
  type?: string | null;
  media_id?: string | null;
  media_kind?: string | null;
  role?: string | null;
  origin?: string | null;
}
export interface FileRef {
  type: string;
  path: string;
  label?: string | null;
  mime_type?: string | null;
}
export interface TaskResult {
  success: boolean;
  files?: FileRef[];
  meta?: Record<string, unknown>;
  error?: string | null;
}
export interface TaskArtifact {
  kind: "video" | "audio" | "subtitle" | "image" | "file";
  role: "input" | "output" | "context";
  ref: MediaReference;
}
export interface TaskResponse {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  task_id: string;
  status: string;
  message?: string;
}
export interface TaskView {
  id: string;
  type: string;
  status: string;
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  progress: number;
  name?: string | null;
  message?: string;
  error?: string | null;
  result?: Record<string, unknown> | null;
  request_params?: Record<string, unknown> | null;
  primary_operation: string;
  artifacts?: TaskArtifact[];
  created_at: number;
  queue_state: string;
  queue_position?: number | null;
}
export interface TranslateResponse {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  task_id: string;
  status: string;
  segments?: import("./task").SubtitleSegment[] | null;
  message?: string;
}
export interface DownloadParams {
  url: string;
  format?: string;
  proxy?: string | null;
  output_dir?: string | null;
  playlist_title?: string | null;
  playlist_items?: string | null;
  download_subs?: boolean;
  resolution?: string;
  cookie_file?: string | null;
  output_filename?: string | null;
  filename?: string | null;
  codec?: string;
}
export interface TranscribeParams {
  audio_ref?: MediaReference | null;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
}
export interface TranslateParams {
  context_ref?: MediaReference | null;
  target_language?: string;
  mode?: string;
  batch_size?: number;
}
export interface SynthesizeParams {
  video_ref?: MediaReference | null;
  srt_ref?: MediaReference | null;
  output_ref?: MediaReference | null;
  watermark_path?: string | null;
  options?: Record<string, unknown> | null;
}
export interface TranscribeRequest {
  audio_ref: MediaReference;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
}
export interface TranscribeSegmentRequest {
  audio_ref: MediaReference;
  engine?: "builtin" | "cli";
  model?: string;
  language?: string | null;
  device?: string;
  vad_filter?: boolean;
  initial_prompt?: string | null;
  start: number;
  end: number;
}
export interface SynthesisRequest {
  video_ref: MediaReference;
  srt_ref: MediaReference;
  watermark_path?: string | null;
  output_ref?: MediaReference | null;
  options?: Record<string, unknown> | null;
}
export interface OCRExtractRequest {
  video_ref: MediaReference;
  roi?: number[] | null;
  engine?: string;
  sample_rate?: number;
}
export interface OCRExtractResponse {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  task_id: string;
  status?: string;
  message?: string;
  events?: TextEvent[] | null;
}
export interface EnhanceRequest {
  video_ref: MediaReference;
  model?: string | null;
  scale?: string;
  method?: string;
}
export interface CleanRequest {
  video_ref: MediaReference;
  roi: number[];
  method?: string;
}
export interface PreprocessingResponse {
  task_source: "backend";
  task_contract_version: number;
  persistence_scope: string;
  lifecycle: string;
  queue_state: string;
  queue_position: number | null;
  primary_operation: string;
  task_id: string;
  status: string;
  message: string;
}
export interface TextEvent {
  start: number;
  end: number;
  text: string;
  box?: number[][];
}
export interface PlaylistItem {
  index: number;
  title: string;
  url: string;
  duration?: number | null;
  uploader?: string | null;
}
export interface AnalyzeResult {
  type: string;
  platform?: string | null;
  id?: string | null;
  title: string;
  url: string;
  direct_src?: string | null;
  thumbnail?: string | null;
  duration?: number | null;
  count?: number | null;
  items?: PlaylistItem[] | null;
  uploader?: string | null;
  webpage_url?: string | null;
  extra_info?: Record<string, unknown> | null;
}
export interface GlossaryTerm {
  id: string;
  source: string;
  target: string;
  note?: string | null;
  category?: string | null;
}
export interface LLMProvider {
  id: string;
  name: string;
  base_url: string;
  api_key: string;
  model: string;
  is_active?: boolean;
}
export interface UserSettings {
  llm_providers?: LLMProvider[];
  default_download_path?: string | null;
  faster_whisper_cli_path?: string | null;
  language?: string;
  auto_execute_flow?: boolean;
  smart_split_text_limit?: number;
  ui_state?: Record<string, unknown>;
}
export interface ActiveProviderRequest {
  provider_id: string;
}
export interface ProviderConnectionRequest {
  name?: string | null;
  base_url: string;
  api_key: string;
  model: string;
}
export interface ToolUpdateResponse {
  status: string;
  message: string;
  previous_version?: string | null;
  current_version?: string | null;
}
export interface FasterWhisperCliInstallResponse {
  status: string;
  message: string;
  cli_path: string;
  version?: string | null;
}
export interface RuntimeDependencyCheck {
  key: string;
  label: string;
  status: string;
  detail: string;
  path?: string | null;
  version?: string | null;
}
export interface CudaReadinessResponse {
  status: string;
  summary: string;
  gpu_name?: string | null;
  driver_version?: string | null;
  driver_cuda_capability?: string | null;
  dependencies: RuntimeDependencyCheck[];
  install_guidance: string[];
}
export interface CreateGlossaryTermRequest {
  source: string;
  target: string;
  note?: string | null;
  category?: string;
}
export interface UpdateGlossaryTermRequest {
  source?: string | null;
  target?: string | null;
  note?: string | null;
  category?: string | null;
}
export interface PipelineRequest {
  pipeline_id?: string;
  task_name?: string | null;
  steps: PipelineStepRequest[];
}
