// Generated by scripts/generate_desktop_worker_api_types.py from contracts/desktop-worker-contract.json.
// Do not edit by hand.

export const DESKTOP_WORKER_INVOCATION_DESCRIPTORS = {
  "desktopPing": {
    "ipcChannel": "desktop:ping",
    "workerCommand": "ping",
    "executionLane": "control"
  },
  "getDesktopSettings": {
    "ipcChannel": "desktop:get-settings",
    "workerCommand": "get_settings",
    "executionLane": "control"
  },
  "updateDesktopSettings": {
    "ipcChannel": "desktop:update-settings",
    "workerCommand": "update_settings",
    "executionLane": "control"
  },
  "setDesktopActiveProvider": {
    "ipcChannel": "desktop:set-active-provider",
    "workerCommand": "set_active_provider",
    "executionLane": "control"
  },
  "testDesktopProvider": {
    "ipcChannel": "desktop:test-provider",
    "workerCommand": "test_provider",
    "executionLane": "control"
  },
  "listDesktopGlossary": {
    "ipcChannel": "desktop:glossary-list",
    "workerCommand": "glossary_list",
    "executionLane": "control"
  },
  "addDesktopGlossaryTerm": {
    "ipcChannel": "desktop:glossary-add",
    "workerCommand": "glossary_add",
    "executionLane": "control"
  },
  "deleteDesktopGlossaryTerm": {
    "ipcChannel": "desktop:glossary-delete",
    "workerCommand": "glossary_delete",
    "executionLane": "control"
  },
  "updateDesktopYtDlp": {
    "ipcChannel": "desktop:update-yt-dlp",
    "workerCommand": "update_yt_dlp",
    "executionLane": "utility"
  },
  "installDesktopFasterWhisperCli": {
    "ipcChannel": "desktop:install-faster-whisper-cli",
    "workerCommand": "install_faster_whisper_cli",
    "executionLane": "utility"
  },
  "analyzeDesktopUrl": {
    "ipcChannel": "desktop:analyze-url",
    "workerCommand": "analyze_url",
    "executionLane": "utility"
  },
  "saveDesktopCookies": {
    "ipcChannel": "desktop:save-cookies",
    "workerCommand": "save_cookies",
    "executionLane": "control"
  },
  "getDesktopOcrResults": {
    "ipcChannel": "desktop:get-ocr-results",
    "workerCommand": "get_ocr_results",
    "executionLane": "control"
  },
  "desktopTranscribeSegment": {
    "ipcChannel": "desktop:transcribe-segment",
    "workerCommand": "transcribe_segment",
    "executionLane": "utility"
  },
  "desktopTranslateSegment": {
    "ipcChannel": "desktop:translate-segment",
    "workerCommand": "translate_segment",
    "executionLane": "utility"
  },
  "uploadDesktopWatermark": {
    "ipcChannel": "desktop:upload-watermark",
    "workerCommand": "upload_watermark",
    "executionLane": "control"
  },
  "getDesktopLatestWatermark": {
    "ipcChannel": "desktop:get-latest-watermark",
    "workerCommand": "get_latest_watermark",
    "executionLane": "control"
  }
} as const;

export type DesktopWorkerInvocationName = keyof typeof DESKTOP_WORKER_INVOCATION_DESCRIPTORS;

export type DesktopWorkerInvocationPayloads = {
  desktopPing: void;
  getDesktopSettings: void;
  updateDesktopSettings: { settings: import("../types/api").UserSettings };
  setDesktopActiveProvider: { provider_id: string };
  testDesktopProvider: import("../types/api").ProviderConnectionRequest;
  listDesktopGlossary: void;
  addDesktopGlossaryTerm: import("../types/api").CreateGlossaryTermRequest;
  deleteDesktopGlossaryTerm: { term_id: string };
  updateDesktopYtDlp: void;
  installDesktopFasterWhisperCli: void;
  analyzeDesktopUrl: { url: string };
  saveDesktopCookies: { domain: string; cookies: import("../types/api").ElectronCookie[] };
  getDesktopOcrResults: { video_ref: import("../types/api").MediaReference };
  desktopTranscribeSegment: import("../types/api").TranscribeSegmentRequest;
  desktopTranslateSegment: import("../types/api").TranslateRequest;
  uploadDesktopWatermark: { file_path: string };
  getDesktopLatestWatermark: void;
};

export type DesktopWorkerInvocationResults = {
  desktopPing: { status: string };
  getDesktopSettings: import("../types/api").UserSettings;
  updateDesktopSettings: import("../types/api").UserSettings;
  setDesktopActiveProvider: { status: string; active_provider_id: string };
  testDesktopProvider: import("../types/api").ProviderConnectionResponse;
  listDesktopGlossary: import("../types/api").GlossaryTerm[];
  addDesktopGlossaryTerm: import("../types/api").GlossaryTerm;
  deleteDesktopGlossaryTerm: { status: string };
  updateDesktopYtDlp: import("../types/api").ToolUpdateResponse;
  installDesktopFasterWhisperCli: import("../types/api").FasterWhisperCliInstallResponse;
  analyzeDesktopUrl: import("../types/api").AnalyzeResult;
  saveDesktopCookies: { domain: string; has_valid_cookies: boolean; cookie_path: string };
  getDesktopOcrResults: import("../types/api").OCRExtractResponse;
  desktopTranscribeSegment: import("../types/api").TranscribeSegmentResponse;
  desktopTranslateSegment: import("../types/api").TranslateResponse;
  uploadDesktopWatermark: import("../types/api").ImagePreviewResponse;
  getDesktopLatestWatermark: import("../types/api").ImagePreviewResponse | null;
};

export type DesktopWorkerPayload<Name extends DesktopWorkerInvocationName> = DesktopWorkerInvocationPayloads[Name];
export type DesktopWorkerResult<Name extends DesktopWorkerInvocationName> = DesktopWorkerInvocationResults[Name];

export type DesktopWorkerBridgeMethod<Name extends DesktopWorkerInvocationName> =
  DesktopWorkerPayload<Name> extends void
    ? () => Promise<DesktopWorkerResult<Name>>
    : (payload: DesktopWorkerPayload<Name>) => Promise<DesktopWorkerResult<Name>>;

export type DesktopWorkerBridgeApi = {
  [Name in DesktopWorkerInvocationName]: DesktopWorkerBridgeMethod<Name>;
};
