// Generated by scripts/generate_frontend_api_types.py from contracts/task-catalog.json.
// Do not edit by hand.

export const TASK_TYPES = ["pipeline"] as const;
export type TaskType = (typeof TASK_TYPES)[number];

export const PIPELINE_STEP_NAMES = ["download", "transcribe", "translate", "synthesize", "clip_export"] as const;
export type PipelineStepName = (typeof PIPELINE_STEP_NAMES)[number];
