// Generated by scripts/generate_frontend_api_types.py from backend.models.translation_target_language.
// Do not edit by hand.

import type { TranslationTargetLanguage } from "../types/generatedApi";
export type { TranslationTargetLanguage } from "../types/generatedApi";

export const TRANSLATION_TARGET_LANGUAGES = [
  { value: "SimplifiedChinese", labelKey: "languages.SimplifiedChinese", suffix: "_ZH-CN" },
  { value: "TraditionalChinese", labelKey: "languages.TraditionalChinese", suffix: "_ZH-TW" },
  { value: "English", labelKey: "languages.English", suffix: "_EN" },
  { value: "Japanese", labelKey: "languages.Japanese", suffix: "_JP" },
  { value: "Spanish", labelKey: "languages.Spanish", suffix: "_ES" },
  { value: "French", labelKey: "languages.French", suffix: "_FR" },
  { value: "German", labelKey: "languages.German", suffix: "_DE" },
  { value: "Russian", labelKey: "languages.Russian", suffix: "_RU" },
] as const satisfies readonly {
  value: TranslationTargetLanguage;
  labelKey: string;
  suffix: string;
}[];

export const DEFAULT_TRANSLATION_TARGET_LANGUAGE: TranslationTargetLanguage =
  "SimplifiedChinese";
