// Generated by scripts/generate_frontend_api_types.py from contracts/runtime-contract.json.
// Do not edit by hand.

export const TASK_MESSAGE_CODES = ["queued", "starting", "running", "completed", "failed", "paused", "cancelled", "deleted", "deleted_count", "pause_requested", "cancellation_requested", "paused_in_queue", "cancelled_in_queue", "interrupted_by_restart", "resumed", "already_running", "already_active", "execution_spec_missing", "pipeline_starting", "pipeline_step_running", "pipeline_step_failed", "pipeline_completed", "download_progress", "download_stage_completed", "download_subtitle_failed", "download_completed", "transcription_starting", "transcription_progress", "transcription_completed", "asr_cli_warmup_waiting", "asr_audio_splitting", "asr_chunks_progress", "asr_model_preparing", "asr_model_downloading", "asr_model_source_fallback", "asr_model_initializing", "asr_model_loaded", "asr_cuda_cpu_fallback", "asr_finalizing", "translation_starting", "translation_batch_progress", "translation_completed", "synthesis_preparing", "synthesis_starting", "synthesis_encoding", "synthesis_completed", "clip_export_preparing", "clip_exporting", "clip_export_completed"] as const;
export type TaskMessageCode = (typeof TASK_MESSAGE_CODES)[number];

export const TASK_STATUSES = ["pending", "running", "completed", "failed", "cancelled", "paused"] as const;
export type TaskStatus = (typeof TASK_STATUSES)[number];

export const TASK_SOURCES = ["backend"] as const;
export type TaskSource = (typeof TASK_SOURCES)[number];

export const TASK_PERSISTENCE_SCOPES = ["runtime", "history"] as const;
export type TaskPersistenceScope = (typeof TASK_PERSISTENCE_SCOPES)[number];

export const TASK_QUEUE_STATES = ["queued", "running", "paused", "cancelled", "completed", "failed", "idle"] as const;
export type TaskQueueState = (typeof TASK_QUEUE_STATES)[number];

export const TASK_LIFECYCLES = ["runtime-only", "history-only", "resumable", "ephemeral-ui"] as const;
export type TaskLifecycle = (typeof TASK_LIFECYCLES)[number];

export const TASK_STATUS_TRANSITIONS = {"pending":["running","paused","cancelled","failed"],"running":["completed","failed","cancelled","paused"],"paused":["pending","cancelled"],"completed":[],"failed":[],"cancelled":[]} as const satisfies Record<TaskStatus, readonly TaskStatus[]>;
