from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = REPO_ROOT / "contracts" / "desktop-worker-contract.json"
OUTPUT_PATH = REPO_ROOT / "frontend" / "src" / "contracts" / "generatedDesktopWorkerApi.ts"


def _required_string(descriptor: dict[str, Any], key: str, name: str) -> str:
    value = descriptor.get(key)
    if not isinstance(value, str) or not value:
        raise RuntimeError(f"Desktop worker {name} is missing {key}")
    return value


def main() -> None:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    invocations = contract.get("invocations")
    if not isinstance(invocations, dict):
        raise RuntimeError("desktop-worker-contract.json is missing invocations")

    lines: list[str] = [
        "// Generated by scripts/generate_desktop_worker_api_types.py from contracts/desktop-worker-contract.json.",
        "// Do not edit by hand.",
        "",
        "export const DESKTOP_WORKER_INVOCATION_DESCRIPTORS = " + json.dumps(
            {
                name: {
                    "ipcChannel": _required_string(descriptor, "ipcChannel", name),
                    "workerCommand": _required_string(descriptor, "workerCommand", name),
                    "executionLane": _required_string(descriptor, "executionLane", name),
                }
                for name, descriptor in invocations.items()
            },
            ensure_ascii=False,
            indent=2,
        ) + " as const;",
        "",
        "export type DesktopWorkerInvocationName = keyof typeof DESKTOP_WORKER_INVOCATION_DESCRIPTORS;",
        "",
        "export type DesktopWorkerInvocationPayloads = {",
    ]

    for name, descriptor in invocations.items():
        lines.append(f"  {name}: {_required_string(descriptor, 'payloadType', name)};")
    lines.extend(["};", "", "export type DesktopWorkerInvocationResults = {"])
    for name, descriptor in invocations.items():
        lines.append(f"  {name}: {_required_string(descriptor, 'resultType', name)};")
    lines.extend(
        [
            "};",
            "",
            "export type DesktopWorkerPayload<Name extends DesktopWorkerInvocationName> = DesktopWorkerInvocationPayloads[Name];",
            "export type DesktopWorkerResult<Name extends DesktopWorkerInvocationName> = DesktopWorkerInvocationResults[Name];",
            "",
            "export type DesktopWorkerBridgeMethod<Name extends DesktopWorkerInvocationName> =",
            "  DesktopWorkerPayload<Name> extends void",
            "    ? () => Promise<DesktopWorkerResult<Name>>",
            "    : (payload: DesktopWorkerPayload<Name>) => Promise<DesktopWorkerResult<Name>>;",
            "",
            "export type DesktopWorkerBridgeApi = {",
            "  [Name in DesktopWorkerInvocationName]: DesktopWorkerBridgeMethod<Name>;",
            "};",
            "",
        ]
    )

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
