from __future__ import annotations

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from backend.models.schemas import TaskResponse, TranslateResponse

OUTPUT = REPO_ROOT / "frontend" / "src" / "types" / "generatedApi.ts"


def _optional(schema: dict, name: str) -> bool:
    return name not in set(schema.get("required", []))


def _field(schema: dict, name: str, ts_type: str) -> str:
    return f"  {name}{'?' if _optional(schema, name) else ''}: {ts_type};"


def main() -> None:
    task_schema = TaskResponse.model_json_schema()
    translate_schema = TranslateResponse.model_json_schema()

    content = "\n".join(
        [
            "// Generated by scripts/generate_frontend_api_types.py from backend.models.schemas.",
            "// Do not edit by hand.",
            "",
            'import type { SubtitleSegment } from "./task";',
            "",
            "export interface TaskResponse {",
            _field(task_schema, "task_id", "string"),
            _field(task_schema, "status", "string"),
            _field(task_schema, "message", "string"),
            "}",
            "",
            "export interface TranslateResponse {",
            _field(translate_schema, "task_id", "string"),
            _field(translate_schema, "status", "string"),
            _field(translate_schema, "segments", "SubtitleSegment[] | null"),
            "}",
            "",
        ]
    )
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
